In [2]:
import pandas as pd
import numpy as np
from gensim.models import Word2Vec

In [5]:
wordvec_model = Word2Vec.load("./word2vec.model")
sept = pd.read_pickle("./pickles/sept.pickle")
tisch = pd.read_pickle("./pickles/tisch.pickle")

In [8]:
tisch

            text   str  verse  chapter  book   rmac
0         βίβλος   976      1        1    40  n-nsf
1       γενέσεως  1078      1        1    40  n-gsf
2          ἰησοῦ  2424      1        1    40  n-gsm
3        χριστοῦ  5547      1        1    40  n-gsm
4           υἱοῦ  5207      1        1    40  n-gsm
...          ...   ...    ...      ...   ...    ...
137520       τοῦ  3588     21       22    66  t-gsm
137521    κυρίου  2962     21       22    66  n-gsm
137522     ἰησοῦ  2424     21       22    66  n-gsm
137523      μετὰ  3326     21       22    66   prep
137524    πάντων  3956     21       22    66  a-gpm

[137525 rows x 6 columns]

In [22]:
sept_verses = list(
    sept.groupby(["book", "chapter", "verse"])["text"]
    .apply(lambda words: " ".join(words))
    .values
)
tisch_verses = list(
    tisch.groupby(["book", "chapter", "verse"])["text"]
    .apply(lambda words: " ".join(words))
    .values
)

In [29]:
tisch_verse_df = pd.DataFrame(data = tisch_verses, columns = ["verse"])
sept_verse_df = pd.DataFrame(data = sept_verses, columns = ['verse'])
display(tisch_verse_df.head(3))

                                               verse
0  βίβλος γενέσεως ἰησοῦ χριστοῦ υἱοῦ δαυεὶδ υἱοῦ...
1  ἀβραὰμ ἐγέννησεν τὸν ἰσαάκ ἰσαὰκ δὲ ἐγέννησεν ...
2  ἰούδας δὲ ἐγέννησεν τὸν φάρες καὶ τὸν ζάρα ἐκ ...

In [38]:
tisch_verse_df.loc[0]

verse    βίβλος γενέσεως ἰησοῦ χριστοῦ υἱοῦ δαυεὶδ υἱοῦ...
Name: 0, dtype: object

In [58]:
def word_vectorise(sentence: str) -> np.array:
    return [
        wordvec_model.wv[word] for word in sentence.split()
    ]

tisch_verse_df['word_vec'] = tisch_verse_df['verse'].apply(word_vectorise)
sept_verse_df['word_vec'] = sept_verse_df['verse'].apply(word_vectorise)
print("length:", len(tisch_verse_df.loc[0, 'word_vec'][0]))
print(tisch_verse_df.loc[0, 'word_vec'][0])

length: 100
[-0.24032982  0.10497052 -0.00308637  0.12362517  0.03880728 -0.1135773
  0.04112744  0.08834936 -0.04992902 -0.16233678  0.00989231 -0.07611354
 -0.14753082 -0.16599429  0.08356807 -0.10447529  0.12230122 -0.15090051
 -0.007137   -0.2618108   0.15207142  0.09956299  0.12369125 -0.08708986
  0.09811371 -0.03301196 -0.0165933  -0.02127917 -0.10825001  0.19434698
 -0.00693271 -0.09223215  0.12313589 -0.1928468   0.02982612  0.21127321
  0.01179363 -0.09655832 -0.05963047 -0.23786303  0.00393754 -0.15463476
  0.05177153  0.05188834 -0.1269504  -0.01086573 -0.14594045  0.06316634
 -0.02595528  0.00191778  0.2375966  -0.08580761  0.08505993 -0.04359898
  0.123184   -0.04595947 -0.15366122  0.02025982 -0.03542252  0.08475615
  0.08588135 -0.02549522  0.07300789 -0.0157127  -0.13504358 -0.01136343
 -0.05524818  0.20966588 -0.13983242  0.00628617  0.12301905  0.2606022
  0.08614439 -0.06940904  0.23480766  0.04027305 -0.10677826  0.16429019
 -0.12122782 -0.19634433 -0.1824819  -0.06179269 -0.00377729  0.11308527
 -0.1724104   0.05091435  0.15274017 -0.04132867  0.26706475  0.25402907
  0.36959937 -0.01400973 -0.15488662 -0.09557797  0.26326838 -0.02506132
 -0.10745304 -0.12574059  0.13235016 -0.14955135]

In [63]:
sept_verse_vecs = sept_verse_df.drop("verse", axis = 1)
tisch_verse_vecs = tisch_verse_df.drop("verse", axis=1)