In [28]:
import pandas as pd
import numpy as np

In [29]:
tisch = pd.read_pickle('tisch')
sept = pd.read_pickle('sept.pickle')

In [30]:
tisch

             text   str verse chapter book   rmac
0         Βίβλος    976     1       1   40  n-nsf
1       γενέσεως   1078     1       1   40  n-gsf
2          Ἰησοῦ   2424     1       1   40  n-gsm
3        Χριστοῦ   5547     1       1   40  n-gsm
4           υἱοῦ   5207     1       1   40  n-gsm
...           ...   ...   ...     ...  ...    ...
137497       τοῦ   3588    21      22   66  t-gsm
137498    κυρίου   2962    21      22   66  n-gsm
137499     Ἰησοῦ   2424    21      22   66  n-gsm
137500      μετὰ   3326    21      22   66   prep
137501    πάντων.  3956    21      22   66  a-gpm

[137502 rows x 6 columns]

In [31]:
nameless = pd.concat(
    [tisch[tisch['str'].isna()],
    sept[sept['str'].isna()]]
)

In [32]:
table = str.maketrans("","", ' .·,:;!()«»-·')
nameless['filt_text'] = nameless['text'].str.translate(table)

In [33]:
nameless['filt_text'].value_counts()

filt_text
δοῦλος        31
δοῦλοι        20
δούλους       18
δοῦλον        17
μῆνας         14
δούλοις        7
δούλου         6
δούλῳ          6
δοῦλε          6
δούλων         5
ἀπὼν           5
εἴγε           5
βάτου          3
τοὐναντίον     3
ἦχος           2
μῆνα           2
δοῦλός         2
μὴν            2
δοῦλα          2
τοὔνομα        1
λοιμοὶ         1
βάτους         1
συνῆσαν        1
Συνιόντος      1
δοῦλόν         1
μηνὶ           1
συνόντων       1
ἤχους          1
δοῦλοί         1
φόρου          1
Ἀππίου         1
λοιμὸν         1
ἀπόντες        1
ἄπειμι         1
Δούλους        1
ἤχῳ            1
Name: count, dtype: int64

In [34]:
indexes = (~nameless['filt_text'].str.fullmatch(r'\w+'))
nameless[indexes]

Empty DataFrame
Columns: [text, str, verse, chapter, book, rmac, filt_text]
Index: []

In [44]:
no_str_words = pd.Series(nameless['filt_text'].unique())
new_strongs = pd.Series(
    'C' + np.arange(len(no_str_words)).astype(str),
    index = no_str_words
)